name: LR
channels:
  - conda-forge
  - gurobi
dependencies:
  - python=3.8
  - numpy
  - pylint
  - pip
  - pandas
  - setuptools
  - matplotlib
  - jupyter
  - gurobi
  - openpyxl
  - pip:
    - scikit_posthocs
  # - pip:
  #   - pip install -e file:PyPruning
  #   - pip install -e file:experiment_runner
    # - pip install git+ssh://git@github.com/sbuschjaeger/PyPruning.git
    # - pip install git+ssh://git@github.com/sbuschjaeger/experiment_runner.git