name: lr
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch 
  - torchvision 
  - torchaudio 
  - cpuonly
  - setuptools
  - matplotlib
  - julia
  # - pylint
  # - gurobi
  # - openpyxl
  - pip
  - pip:
    - psutil
    - scikit_posthocs
    - pip install git+https://github.com/sbuschjaeger/PyPruning.git
    - pip install git+https://github.com/sbuschjaeger/fastinference.git
