name: lr
channels:
  - pytorch
  - conda-forge
  - gurobi
dependencies:
  - python=3.8
  - numpy
  - pylint
  - pip
  - pandas
  - setuptools
  - matplotlib
  - jupyter
  - gurobi
  - openpyxl
  - pytorch 
  - torchvision 
  - torchaudio 
  - pip
  - pip:
    - scikit_posthocs
#    - pip install https://github.com/sbuschjaeger/PyPruning.git